### ISSUE TITLE
go get fails ??

### ISSUE THREAD

**Issue by gedw99** [g3n/g3nd#13]
just trying this out

x-MacBook-Pro:3gn apple$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build769837385=/tmp/go-build -gno-record-gcc-switches -fno-common"

go get -u -v github.com/g3n/g3nd
github.com/g3n/g3nd (download)
github.com/g3n/engine (download)
github.com/go-gl/glfw (download)
github.com/golang/freetype (download)
Fetching https://golang.org/x/image/math/fixed?go-get=1
Parsing meta tags from https://golang.org/x/image/math/fixed?go-get=1 (status code 200)
get "golang.org/x/image/math/fixed": found meta tag get.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at https://golang.org/x/image/math/fixed?go-get=1
get "golang.org/x/image/math/fixed": verifying non-authoritative meta tag
Fetching https://golang.org/x/image?go-get=1
Parsing meta tags from https://golang.org/x/image?go-get=1 (status code 200)
golang.org/x/image (download)
Fetching https://golang.org/x/image/font?go-get=1
Parsing meta tags from https://golang.org/x/image/font?go-get=1 (status code 200)
get "golang.org/x/image/font": found meta tag get.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at https://golang.org/x/image/font?go-get=1
get "golang.org/x/image/font": verifying non-authoritative meta tag
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/kardianos/osext (download)
github.com/g3n/engine/audio/vorbis
github.com/g3n/engine/audio/al
github.com/g3n/engine/audio/ov
# github.com/g3n/engine/audio/vorbis
../../../../../../github.com/g3n/engine/audio/vorbis/vorbis.go:15:11: fatal error: 'codec.h' file not found
 #include "codec.h"
          ^~~~~~~~~
1 error generated.
# github.com/g3n/engine/audio/ov
../../../../../../github.com/g3n/engine/audio/ov/vorbisfile.go:16:11: fatal error: 'vorbisfile.h' file not found
 #include "vorbisfile.h"
          ^~~~~~~~~~~~~~
1 error generated.
# github.com/g3n/engine/audio/al
../../../../../../github.com/g3n/engine/audio/al/al.go:19:10: fatal error: 'al.h' file not found
#include "al.h"
         ^~~~~~
1 error generated.
make: *** [dep] Error 2

**Comment by leonsal** [comment]
OS X is not supported. We do not have access to a Mac.
Have you installed the dependencies ?

**Comment by gedw99** [comment]
yes but fails.

you should check this out.
https://github.com/hajimehoshi/ebiten/blob/master/audio/vorbis/vorbis.go

works on all Desktops.

**Comment by gedw99** [comment]
I had another go today.

Works on Mac perfectly !
Just brew install and thats it.

Great stuff - amazing work

**Comment by danaugrs** [comment]
Awesome! Thanks for letting us know.

**Comment by sovrinbloc** [comment]
@gedw99  how did you get it working? you provided no solution. I am getting, 
```
/Users/joealai/go/src/github.com/danaugrs/gokoban/vendor/github.com/g3n/engine/audio/vorbis/vorbis.go:15:11: fatal error: 'codec.h' file not found
 #include "codec.h"
          ^~~~~~~~~
1 error generated.
# github.com/danaugrs/gokoban/vendor/github.com/g3n/engine/audio/al
/Users/joealai/go/src/github.com/danaugrs/gokoban/vendor/github.com/g3n/engine/audio/al/al.go:19:10: fatal error: 'al.h' file not found
#include "al.h"
         ^~~~~~
1 error generated.
# github.com/danaugrs/gokoban/vendor/github.com/g3n/engine/audio/ov
/Users/joealai/go/src/github.com/danaugrs/gokoban/vendor/github.com/g3n/engine/audio/ov/vorbisfile.go:16:11: fatal error: 'vorbisfile.h' file not found
 #include "vorbisfile.h"
```

**Comment by curiouscod3** [comment]
Same Error!

 go get -u github.com/g3n/g3nd
# github.com/g3n/engine/audio/al
src/github.com/g3n/engine/audio/al/al.go:21:10: fatal error: 'al.h' file not found
#include "al.h"
         ^~~~~~
1 error generated.
# github.com/go-gl/glfw/v3.2/glfw
In file included from src/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:
In file included from ./glfw/src/context.c:28:
In file included from ./glfw/src/internal.h:165:
In file included from ./glfw/src/cocoa_platform.h:31:
/usr/include/dlfcn.h:40:10: fatal error: 'stdbool.h' file not found
#include <stdbool.h>
         ^~~~~~~~~~~
1 error generated.
# github.com/g3n/engine/gls
In file included from glapi.c:57:
/usr/include/dlfcn.h:40:10: fatal error: 'stdbool.h' file not found

**Comment by danaugrs** [comment]
@curiouscod3 did you run `brew install libvorbis openal-soft` ?
