### ISSUE TITLE
glad to have demos: multi viewport,  and multi windows with separate scene inside,   

### ISSUE THREAD

**Issue by finomxf** [g3n/g3nd#14]
as a beginner of opengl and 3D graphics, I would like to require such demos: 

what I suppose: 

1) multi viewport:  one scene, different camera ,  one camera for one viewport,  

[https://doc.qt.io/qt-5.10/images/multiviewport.png](https://doc.qt.io/qt-5.10/images/multiviewport.png)

2) multi windows with separate scene inside:

sometimes we need to display several un-related scenes in one application,  then I think viewport may not able to do this,  maybe multi child windows are needed, each child window display a unique scene inside, 
[https://learnopengl.com/img/advanced-lighting/deferred_g_buffer.png](https://learnopengl.com/img/advanced-lighting/deferred_g_buffer.png)

thanks! 

BR fino

**Comment by danaugrs** [comment]
Hi! We don't have plans to support multiple windows, but we do want to support multiple viewports.
I'm not sure when we'll have the bandwidth to work on that.
If you implement it please make a pull request!

**Comment by danaugrs** [comment]
Closing in favor of https://github.com/g3n/engine/issues/132
