### ISSUE TITLE
horizontal scroll in the 2D GUI

### ISSUE THREAD

**Issue by gedw99** [g3n/g3nd#18]
Everything works well on a mac, but the horizontal scroll does not quite work properly.

The best GUI control to test this is the "Scroller"

On the trackpad Vertical scroll works perfect. 2 fingers and it scrolls like silk.
For Horizontal, you have to move the cursor down onto the horizontal scrollbar, and then the 1 finger click and hold on the trackpad.

If i turn the "ScrollHorizontal" on, then the 2 finger horizontal works, so the API hooks do work for MAC. But you have to drag the 2 finger UP, to scroll horizontally.

So it feels like maybe a little bit of adjustment in the code is needed.

I can make a screenshot if needed.

**Comment by danaugrs** [comment]
Hi - thanks for the report.
I fixed trackpad horizontal scrolling in https://github.com/g3n/engine/commit/cb0b7b7e2db5377c79e0304b96a9550f7396aaa3.
Note that the correction is in the `Scroller` class and therefore `ItemScroller` instances will still have this issue. We intend to derive all scrollable GUI elements from `Scroller` in the future.
Please try again with the latest version and let me know if it works!

**Comment by gedw99** [comment]
Will check it in next few days . Mad crazy . If I forget buzz me again here

**Comment by gedw99** [comment]
@danaugrs i just tested it with all the radio and checkbox toggles on the scroller demo.
Works perfectly on my Mac.... ! Great stuff.
Closing... Open if you have any further questions

**Comment by gedw99** [comment]
reopening.. I guess we need to make another issue to upgrade all gui code to use the **Scroller**, and not **ItemScroller** ?

**Comment by danaugrs** [comment]
Hey - yeah, I just created https://github.com/g3n/engine/issues/69 to track that.
