### ISSUE TITLE
Beginners Issues

### ISSUE THREAD

**Issue by thenetautohub** [g3n/g3nd#20]
Hi Guys,

Sorry for some of the newbieness here but I am struggling to find any documentation on how to do the simplest things.

For instance creation of a blank window, from what I can see of the code the the app struct can initialise a window for me but this seems to come with a load of stuff that I don't need, I have also looked at the recommended game and I can see that they don't use an app, and from both I can see they use the following pattern to start the window initialisation.

`	
        // Window event handling must run on the main OS thread
	runtime.LockOSThread()

	// Get the window manager
	Win , err := window.Manager("glfw")
	if err != nil {
		panic(err)
	}
`

after which they use this to create a window, the issue is that is I try to use this pattern I get 

`image: unknown format`

and cant seem to get to the window setup.

any newb help would be great, a doc would be even better.

thanks

John

**Comment by danaugrs** [comment]
Hi! If you don't want to use the Application object try starting out based on [hellog3n-no-app](https://github.com/g3n/demos/tree/master/hellog3n-no-app). Let me know here if you encounter any issues and we'll work to resolve them!

**Comment by thenetautohub** [comment]
Ok so that demo works, with all the code copied in. however if I strip it back to the following;

`func main() {

	// Creates window and OpenGL context
	wmgr, err := window.Manager("glfw")
	if err != nil {
		panic(err)
	}
	win, err := wmgr.CreateWindow(800, 600, "Hello G3N", false)
	if err != nil {
		panic(err)
	}
	fmt.Println(win)
}`

I get the error from the `wmgr, err := window.Manager("glfw")` line, with the error mentioned before, and as this is the code from the first line I can only assume there is some kind of initilization happening that I am unaware of ?

thanks 

John

**Comment by thenetautohub** [comment]
After doing a little debugging, it would appear that there is something that is required in the

	"github.com/g3n/engine/material"

package to add a window. as soon as Imported this module the initialisation worked and I get past the creation of the window manager, should the window manager be tied to this ?

**Comment by danaugrs** [comment]
Ok so this is happening because g3n is loading some custom cursors (diagonal resize cursors). Interestingly this error doesn't happen when you import the `material` package. I'm investigating...

**Comment by danaugrs** [comment]
Oops you beat me to it. It definitely shouldn't be tied to material.

**Comment by danaugrs** [comment]
I just fixed it: https://github.com/g3n/engine/commit/9d6952a24f8b3f0ab877138f205b752b236af655. Please get latest and try again 👍

**Comment by thenetautohub** [comment]
:+1: 

Fix is working, thanks for the swift help :-)

John

**Comment by danaugrs** [comment]
Glad to hear it. Thanks for helping make g3n better!
