### ISSUE TITLE
Run on mobiles using flutter

### ISSUE THREAD

**Issue by ghost** [g3n/g3nd#22]
I think I can get this going..

https://github.com/mogol/opengl_texture_widget_example

The flutter Texture object is how it's done 
I run golang code inside flutter now so there is a good chance here it will work.

If anyone else is interested let me know 

Best way will be to take the g3nd demo and remove the side nav and let flutter do that bit. Then we can run the exact same demos that it runs on desktop.

Anyone holler if your interested in this as I might need help from the core Devs

**Comment by danaugrs** [comment]
Mobile support is being discussed here: https://github.com/g3n/engine/issues/114
