### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by RUSshy** [g3n/g3nd#23]
Hello

This is super slow to compile, even on a simple hello world

Is cgo that bad ?

How to make it compile fast like a normal go project ?

**Comment by danaugrs** [comment]
It's not at all slow and you only need to compile G3N once. You must be doing something wrong. What steps are you taking to compile and run `hellog3n`?

**Comment by RUSshy** [comment]
```go
package main

import (
	"github.com/g3n/engine/geometry"
	"github.com/g3n/engine/graphic"
	"github.com/g3n/engine/light"
	"github.com/g3n/engine/material"
	"github.com/g3n/engine/math32"
	"github.com/g3n/engine/util/application"
)

func main() {

	app, _ := application.Create(application.Options{
		Title:  "RPG",
		Width:  1280,
		Height: 720,
	})

	// Create a blue torus and add it to the scene
	geom := geometry.NewTorus(1, .4, 12, 32, math32.Pi*2)
	mat := material.NewPhong(math32.NewColor("DarkBlue"))
	torusMesh := graphic.NewMesh(geom, mat)
	app.Scene().Add(torusMesh)

	// Add lights to the scene
	ambientLight := light.NewAmbient(&math32.Color{1.0, 1.0, 1.0}, 0.8)
	app.Scene().Add(ambientLight)
	pointLight := light.NewPoint(&math32.Color{1, 1, 1}, 5.0)
	pointLight.SetPosition(1, 0, 2)
	app.Scene().Add(pointLight)

	// Add an axis helper to the scene
	axis := graphic.NewAxisHelper(0.5)
	app.Scene().Add(axis)

	app.CameraPersp().SetPosition(0, 0, 3)
	app.Run()
}
```

``go build myfile.go``

It takes 5+ seconds to recompile

**Comment by danaugrs** [comment]
It takes a couple hundred milliseconds for me. Can you `go install -v` instead and post the output?

**Comment by RUSshy** [comment]
```
C:\Users\RUS\go\src\awesomeProject>go install -v
awesomeProject
```

**Comment by RUSshy** [comment]
I'm using go 1.11 on windows 10 x64

**Comment by danaugrs** [comment]
I just updated my Go version to 1.11 and it still takes the couple hundred milliseconds for me. Are you sure that you only experience this delay with the G3N demo, and not with other Go applications? If so you should remove parts of the demo code (in a binary search kind of way) until it's clear what portion is causing the delay for you. Let me know what it is and I can try to help figure out why.
