### ISSUE TITLE
osx hit testing is off

### ISSUE THREAD

**Issue by glycerine** [g3n/g3nd#28]
on darwin, the hit testing of mouse clicks is off; I can't directly click the left side tree items and have the clicked one expand. Instead, one much farther down expands (implying it is probably the vertical click location computation that is bugged), or nothing happens at all.

go1.12.7, osx 10.13.6, g3nd 4a8cdd4, engine 6787e56af6f2a7173c5f5cc492bdc72c7d02cb37

edit: another example is on the gui->chart. I can't check and uncheck the check boxes.

**Comment by danaugrs** [comment]
Thanks for the bug report! We try to take the HiDPI scaling into account for mouse events here:

https://github.com/g3n/engine/blob/6787e56af6f2a7173c5f5cc492bdc72c7d02cb37/window/glfw.go#L317-L329

Unfortunately I don't have a MacOS system to test on. It would be highly appreciated if you or anyone who has could take a look at this.

To build and run g3nd using your own local version of the engine you can just add
```
replace github.com/g3n/engine => ../engine
```
to the end of **g3nd**'s `go.mod` file.

**Comment by glycerine** [comment]
the following insertion of `) //` on lines glfw.go:355-356 fixes the issue for me; on my mac.
~~~
    // Set up window cursor position callback to dispatch event
    w.SetCursorPosCallback(func(x *glfw.Window, xpos float64, ypos float64) {
        w.cursorEv.Xpos = float32(xpos) //  * w.scaleX)  // line 355, glfw.go
        w.cursorEv.Ypos = float32(ypos) //  * w.scaleY)   // line 356
        w.cursorEv.Mods = w.mods
        w.Dispatch(OnCursor, &w.cursorEv)
    })
~~~

**Comment by danaugrs** [comment]
Thanks! I'll incorporate that into the engine shortly.

**Comment by danaugrs** [comment]
Fixed by https://github.com/g3n/engine/commit/13e8582dadaad1fdd600040ab26edda7c0ae7b48.
