### ISSUE TITLE
Program freezes at grey screen on startup

### ISSUE THREAD

**Issue by IronGopher** [g3n/g3nd#3]
$ go version
    go version go1.8 linux/amd64

(Although this also occurred when I was using 1.6.2.) I am running Ubuntu GNOME 16.04.2. When I compile and run the program, by entering the directory and running `go build`, a plain gray window appears and nothing happens.

Here is the output when I invoke the program with `./g3nd -logs=gui:debug,gls:debug`:

```
01:21:43.762537:I:G3ND:G3N Demo v0.1 starting
01:21:43.762569:I:G3ND:Set log level:DEBUG for package:GUI
01:21:43.762581:I:G3ND:Set log level:DEBUG for package:GLS
01:21:43.762597:I:G3ND:Using data directory:data
01:21:43.818911:I:G3ND:OpenGL version: 3.3 (Core Profile) Mesa 12.0.6
01:21:43.826131:I:G3ND:OpenAL Community version: 1.1 ALSOFT 1.16.0
01:21:43.826773:I:G3ND:Xiph.Org libVorbis 1.3.5
01:21:43.831008:W:G3N/GUI:Invalid panel width:-202
01:21:43.831717:W:G3N/GUI:Invalid panel width:-306
01:21:43.836590:W:G3N/GUI:Invalid panel width:-306
01:21:43.836635:W:G3N/GUI:Invalid panel height:-48
01:21:43.836653:W:G3N/GUI:Invalid panel width:-306
01:21:43.836663:W:G3N/GUI:Invalid panel height:-48
01:21:43.836671:W:G3N/GUI:Invalid panel width:-202
01:21:43.836677:W:G3N/GUI:Invalid panel height:-48
```

**Comment by leonsal** [comment]
It seems to be a bug in the engine (https://github.com/g3n/engine) which was fixed recently.
Have you tried to update the engine and rebuild the demo ?
```
>cd ....go/src/github.com/g3n/engine 
>git pull
>cd ....go/src/github.com/g3n/g3nd
>go build

```

**Comment by IronGopher** [comment]
"git pull" claims I am already up to date. In case there is something wrong, I am on branch master at commit 9910bd95f6dc3b1dc7e67e892a0a8d48fa490469.

**Comment by IronGopher** [comment]
Everything works now. Thanks.
