### ISSUE TITLE
material->blending glitches

### ISSUE THREAD

**Issue by xyproto** [g3n/g3nd#5]
Hi,

I just tried the g3nd demo and I'm pretty impressed with it. Firstly, it builds and runs just fine (not every 3D framework/engine does this!). Object loading and textures works, and there is a wide selection of GUI controls. At a glance, the code also looks very clear and readable. Thanks for releasing it as open source!

The only issue I could spot were some artifacts when testing the blending:

![blend mode](https://i.imgur.com/jFU7Ixo.png)

I'm on 64-bit Arch Linux with a `Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller`, using the `i915` kernel module.

I would be happy to run test code on my system, if that would help.

Cheers!

**Comment by lanybass** [comment]
mee to

**Comment by leonsal** [comment]
It should be fixed (or greatly reduced) now. Update the engine and rebuild the demo:
```
>cd <GOPATH>/src/github.com/g3n/engine
>git pull
>cd <GOPATH>/src/github.com/g3n/g3nd
>go build  # or go install
```
Thanks for the comments.

**Comment by xyproto** [comment]
Works here now. Thanks for fixing.
